swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8082'
basePath: /ingestion/v1
tags:
  - name: submit-api
    description: Submit Api
paths:
  /submit:
    post:
      tags:
        - submit-api
      summary: submit
      operationId: submitUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: Content-Type
          in: header
          description: The file type/format of the request body
          required: true
          type: string
          default: application/json
        - name: data-partition-id
          in: header
          description: Which tenant to use
          required: true
          type: string
          default: opendes
        - in: body
          name: request
          description: request
          required: true
          schema:
            $ref: '#/definitions/SubmitRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SubmitResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /submitWithManifest:
    post:
      tags:
        - submit-api
      summary: submitWithManifest
      operationId: submitWithManifestUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: Content-Type
          in: header
          description: The file type/format of the request body
          required: true
          type: string
          default: application/json
        - name: data-partition-id
          in: header
          description: Which tenant to use
          required: true
          type: string
          default: opendes
        - in: body
          name: loadManifest
          description: loadManifest
          required: true
          schema:
            $ref: '#/definitions/WorkProductLoadManifest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SubmitResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

definitions:
  'Map«string,object»':
    type: object
    title: 'Map«string,object»'
    additionalProperties:
      type: object
  SubmitRequest:
    type: object
    properties:
      Context:
        type: object
      DataType:
        type: string
      FileID:
        type: string
    title: SubmitRequest
  SubmitResponse:
    type: object
    properties:
      WorkflowID:
        type: string
    title: SubmitResponse
  WorkProductLoadManifest:
    type: object
    properties:
      Files:
        type: array
        items:
          $ref: '#/definitions/Map«string,object»'
      WorkProduct:
        type: object
      WorkProductComponents:
        type: array
        items:
          $ref: '#/definitions/Map«string,object»'
    title: WorkProductLoadManifest
