swagger: '2.0'
info:
  description: API documentation for Partition service
  version: '1.0.0'
  title: Partition
  contact:
    name: OSDU Support
    email: devportal-help@osdu.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
basePath: /api/partition/v1
tags:
  - name: partition-api
    description: Partition Api
  - name: health-check
    description: Health Check
paths:
  /_ah/liveness_check:
    get:
      tags:
        - health-check
      summary: livenessCheck
      operationId: livenessCheckUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - JWT:
            - global
  /_ah/readiness_check:
    get:
      tags:
        - health-check
      summary: readinessCheck
      operationId: readinessCheckUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - JWT:
            - global
  '/partitions/{partitionId}':
    get:
      tags:
        - partition-api
      summary: get
      operationId: getUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: partitionId
          in: path
          description: partitionId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              "$ref": "#/definitions/Property"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - JWT:
            - global
  '/partitions':
    get:
      tags:
        - partition-api
      summary: list
      operationId: listUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - JWT:
            - global
    post:
      tags:
        - partition-api
      summary: create
      operationId: createUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: partitionId
          in: path
          description: partitionId
          required: true
          type: string
        - in: body
          name: partitionInfo
          description: partitionInfo
          required: true
          schema:
            $ref: '#/definitions/PartitionInfo'
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - JWT:
            - global
    patch:
      tags:
      - partition-api
      summary: update
      operationId: updateUsingPATCH
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: partitionId
        in: path
        description: partitionId
        required: true
        type: string
      - in: body
        name: partitionInfo
        description: partitionInfo
        required: true
        schema:
          $ref: '#/definitions/PartitionInfo'
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
      - JWT:
        - global
    delete:
      tags:
        - partition-api
      summary: delete
      operationId: deleteUsingDELETE
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: partitionId
          in: path
          description: partitionId
          required: true
          type: string
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - JWT:
            - global
securityDefinitions:
  JWT:
    type: apiKey
    name: Authorization
    in: header
definitions:
  PartitionInfo:
    type: object
    required:
      - properties
    properties:
      properties:
        type: object
        description: 'Free form key value pair object for any data partition specific values'
        additionalProperties:
          "$ref": "#/definitions/Property"
    example:
      properties:
        compliance-ruleset:
          sensitive: false
          value: 'shared'
        elastic-endpoint:
          sensitive: true
          value: 'elastic-endpoint'
        cosmos-connection:
          sensitive: true
          value: 'cosmos-connection'
  Property:
    type: object
    properties:
      sensitive:
        type: boolean
      value:
        type: object